### ISSUE TITLE
require.paths is removed. Use node_modules folders, or the NODE_PATH environment variable instead.

### ISSUE THREAD

**Issue by AgoristRadio** [balupton/nowpad#9]
The "sys" module is now called "util". It should have a similar interface.
require.paths is removed. Use node_modules folders, or the NODE_PATH environment variable instead.
Error: require.paths is removed. Use node_modules folders, or the NODE_PATH environment variable instead.
    at Function.<anonymous> (module.js:376:11)
    at Object.<anonymous> (/mnt/ws/users/agoristradio/137414/node_modules/buildr/node_modules/less-bal/lib/less/index.js:5:8)

**Comment by balupton** [comment]
https://github.com/balupton/nowpad/issues/11
